config/routes.rb
Rails.application.routes.draw do

  resources :transactions

  get 'filter_transaction', to: 'home#filter_transactions'

  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#log_in'
  delete '/sign_out', to: 'sessions#log_out'

  get 'home/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  validates :amount, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :transaction_type, presence: true
  validates :description, presence: true

  enum :transaction_type, { deposit: 0, atm_out: 1, transfer_in: 2 }

  default_scope { order(time: :desc) }

  scope :for_today, -> { where(date: Date.today) }
  scope :for_this_week, -> { where('date > ?', Date.today.beginning_of_week - 1.day).where('date < ?', Date.today.end_of_week + 1.day) }
  scope :for_this_month, ->{ where('date > ?', Date.today.beginning_of_month - 1.day).where('date < ?', Date.today.end_of_month + 1.day) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :transactions

  validates :username, presence: true
  validates_uniqueness_of :username, on: :create, message: "must be unique", if: proc { User.active.find_by_username(username).nil?.! }

  enum :role, {staff: 0, admin: 1}
  enum :status, { active: 0, inactive: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def logged_in?
    redirect_to sign_in_path unless session[:username].present?
  end

  def current_user
    @current_user ||= User.find_by_username(session[:username])
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in?, :set_transaction_types, :current_user
  before_action :admin_user?, only: :filter_transactions

  def index
    @transactions = current_user.transactions.for_today if current_user.staff?
    if current_user.admin?
      @transactions = Transaction.includes(:user).for_today
      @staff_names = User.active.pluck(:username)
    end
  end


  def filter_transactions
    @staff_names = User.pluck(:username)
    if params[:filter][:staff_name]
      @criteria = 'Staff Name'
      @transactions = Transaction.where( user_id: User.find_by_username(params[:filter][:staff_name]).id )
    elsif params[:filter][:start_date].present? && params[:filter][:end_date].present?.!
      @criteria = 'Start Date only'
      @transactions = Transaction.where('date >= ?', params[:filter][:start_date])
    elsif params[:filter][:start_date].present? && params[:filter][:end_date].present?
      @criteria = 'Start and End Date'
      @transactions = Transaction.where('date >= ?', params[:filter][:start_date]).where('date <= ?', params[:filter][:end_date])
    else
      redirect_to root_path and return
    end
    render :index
  end

  private

  def admin_user?
    current_user.admin?
  end

  def set_transaction_types
    @transaction_types ||= Transaction.transaction_types.keys
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def log_in
    @user = User.find_by_username(params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:username] = params[:user][:username]
      redirect_to root_path, notice: "Signed in successfully!" 
    else
      puts @user.authenticate(params[:user][:password]) if @user
      render :new, status: :unprocessable_entity
    end
  end

  def log_out
    session[:username] = nil
    redirect_to sign_in_path, notice: "Signed out successfully!"
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    if @transaction = current_user.transactions.create(transaction_params)
      redirect_to root_path, notice: "Transaction saved successfully!"
    else
      redirect_to root_path, notice: "Transaction not saved"
    end
  end

  def index
  end

  def destroy
  end

  private
  def transaction_params
    params.require(:transaction).permit(:transaction_type, :amount, :charges, :description).merge(trans_date_and_time)
  end

  def trans_date_and_time
    { date: Date.today, time: Time.now }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/home/index.html.erb
<div class="welcome_message">
  Welcome <%= @current_user.username.titlecase %>
</div>   
<%= button_to 'Log Out', sign_out_path, method: :delete %>

<div class="">
  <p>
    New Transaction
  </p>

  <%= form_for :transaction, :url => transactions_path, html: {class: "form-inline", role:"form"} do |f| %>
    <div class="form-group">
      <%= f.label :transaction_type, 'Transaction Type' %>
      <%= f.select :transaction_type, options_for_select(@transaction_types), class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, '(hint: Account Number)' %>
      <%= f.text_field :description, class:"form-control" %>
    </div>
    <br />
 

    <div class="form-group">
      <%= f.label :amount %>
      <%= f.text_field :amount, class:"form-control", placeholder: '0' %>
    </div>
    <br />

    <div class="form-group">
      <%= f.label :charges %>
      <%= f.text_field :charges, class:"form-control", placeholder: '0' %>
    </div>
    <br />

    <%= f.submit "Save Transaction", class: "btn btn-primary disabled", id: "transaction_button" %>
  <% end %>
</div>

<br />

<% if current_user.admin?%>
  <div class="row mb-3 text-center">
    <div class="col-4">
      <p>Filter By Staff Name</p>
      <%= form_for :filter, :url => filter_transaction_path, method: :get do |f| %>
        <%= f.select :staff_name, options_for_select(@staff_names) %>
        <%= f.submit "Filter", class: "btn btn-success btn-sm" %>
      <% end %>
    </div>

    <div class="col-6">
      <p>Filter By Date</p>
      <%= form_for :filter, :url => filter_transaction_path, method: :get do |f| %>
        <%= f.label :start_date%>
        <%= f.date_field :start_date %>
        <%= f.label :end_date%>
        <%= f.date_field :end_date %>
        <%= f.submit "Filter" , class: "btn btn-success btn-sm" %>
      <% end %>
    </div>
  </div>
<% end %>

<% if @criteria %>
  <p>Filtered by: <%= @criteria %></p>
<% end %>

<div class="">
  <table class="table table-bordered">
    <thead>
      <th>Type</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Charges</th>
      <th>Date</th>
      <th>Staff Name</th>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td>
            <%= transaction.transaction_type.split('_').join(' ').titlecase %>
          </td>
          <td>
            <%= transaction.description %>
          </td>
          <td>
            <%= transaction.amount %>
          </td>
          <td>
            <%= transaction.charges %>
          </td>
          <td>
            <%= transaction.date %>
          </td>
          <td>
            <%= transaction.user.username %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2">Totals</td>
        <td>
          <%= @transactions.pluck(:amount).sum %>
        </td>
        <td>
          <%= @transactions.pluck(:charges).sum %>
        </td>
        <td></td>
        
      </tr>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Point of Sale Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container-sm">
    <%= yield %>
  </body>

  <script>
    let charges_input = document.querySelector("#transaction_charges")
    let transaction_button = document.querySelector("#transaction_button")

    if (charges_input && transaction_button) {
      charges_input.addEventListener("change", () => {
        if (charges_input.value >= 100) {
        transaction_button.classList.remove("disabled")  
        } else {
          transaction_button.classList.add("disabled")  
        }
      })
    }
  </script>
</html>

app/views/transactions/index.html.erb
<h1>Transactions#index</h1>
<p>Find me in app/views/transactions/index.html.erb</p>